alter default privileges for role "postgres" in schema "public" revoke all on sequences from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "service_role";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "service_role";

create table "public"."ai_chats" (
  "id"         uuid                        not null default gen_random_uuid(),
  "user_id"    uuid,
  "company_id" uuid,
  "question"   text                        not null,
  "answer"     text                        not null,
  "created_at" timestamp without time zone default now(),
  constraint "ai_chats_pkey" primary key (id)
);

alter table "public"."ai_chats"
  enable row level security;

create table "public"."companies" (
  "id"               uuid                        not null default gen_random_uuid(),
  "user_id"          uuid,
  "name"             text                        not null,
  "industry"         text,
  "stage"            text,
  "description"      text,
  "target_customers" text,
  "business_model"   text,
  "current_problem"  text,
  "main_goal"        text,
  "created_at"       timestamp without time zone default now(),
  constraint "companies_pkey" primary key (id)
);

alter table "public"."companies"
  enable row level security;

create table "public"."company_memory" (
  "id"         uuid                     not null default gen_random_uuid(),
  "user_id"    uuid                     not null,
  "company_id" uuid                     not null,
  "source"     text                     not null,
  "title"      text,
  "content"    text                     not null,
  "created_at" timestamp with time zone default now(),
  constraint "company_memory_pkey" primary key (id)
);

alter table "public"."company_memory"
  enable row level security;

create table "public"."reports" (
  "id"            bigint                   generated by default as identity not null,
  "created_at"    timestamp with time zone not null default now(),
  "user_id"       uuid                     default gen_random_uuid(),
  "goal"          text,
  "health_score"  smallint,
  "risks"         jsonb,
  "opportunities" jsonb,
  "next_actions"  jsonb,
  "roadmap"       jsonb,
  constraint "reports_pkey" primary key (id)
);

alter table "public"."reports"
  enable row level security;

alter table "public"."ai_chats"
  add constraint "ai_chats_user_id_fkey" foreign key (user_id) references auth.users(id) on delete cascade;

alter table "public"."ai_chats"
  add constraint "ai_chats_company_id_fkey" foreign key (company_id) references public.companies(id) on delete cascade;

alter table "public"."companies"
  add constraint "companies_user_id_fkey" foreign key (user_id) references auth.users(id) on delete cascade;

alter table "public"."company_memory"
  add constraint "company_memory_company_id_fkey" foreign key (company_id) references public.companies(id) on delete cascade;

alter table "public"."company_memory"
  add constraint "company_memory_user_id_fkey" foreign key (user_id) references auth.users(id) on delete cascade;

create policy "Authenticated users can create own chats" on "public"."ai_chats"
  for insert
  to "authenticated"
  with check ((auth.uid() = user_id));

create policy "Users can view own chats" on "public"."ai_chats"
  for select
  to PUBLIC
  using ((auth.uid() = user_id));

create policy "Authenticated users can create own company" on "public"."companies"
  for insert
  to "authenticated"
  with check ((auth.uid() = user_id));

create policy "Users can update own company" on "public"."companies"
  for update
  to PUBLIC
  using ((auth.uid() = user_id));

create policy "Users can view own company" on "public"."companies"
  for select
  to PUBLIC
  using ((auth.uid() = user_id));

create policy "Users can delete own company memory" on "public"."company_memory"
  for delete
  to "authenticated"
  using ((auth.uid() = user_id));

create policy "Users can insert own company memory" on "public"."company_memory"
  for insert
  to "authenticated"
  with check ((auth.uid() = user_id));

create policy "Users can read own company memory" on "public"."company_memory"
  for select
  to "authenticated"
  using ((auth.uid() = user_id));

create policy "Users can update own company memory" on "public"."company_memory"
  for update
  to "authenticated"
  using ((auth.uid() = user_id))
  with check ((auth.uid() = user_id));

create policy "Users can manage own reports" on "public"."reports"
  for all
  to "authenticated"
  using ((auth.uid() = user_id))
  with check ((auth.uid() = user_id));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."ai_chats" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."companies" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."company_memory" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."reports" to "anon", "authenticated", "postgres", "service_role";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "anon";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "authenticated";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "service_role";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "anon";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "authenticated";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "service_role";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "anon";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "authenticated";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "service_role";

